# Generated by Django 4.2.6 on 2023-10-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category_photo_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
