# Generated by Django 4.2.6 on 2023-10-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_photo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
